name: Windows x64 PR 10057 test

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  GIT_SHA: ${{ github.sha }}
  CMAKE_CONFIGURE: cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DSKIP_BUILD_TESTS=ON -DCMAKE_COMPILE_WARNING_AS_ERROR=ON

jobs:
  windows-x64:
    name: Windows x64
    runs-on: windows-2022
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: sithlord48/fancy-checkout@v2

      - name: Setup VC++ environment
        uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: amd64
          spectre: true

      - name: Install dependencies
        id: get-deps
        uses: ./.github/actions/install-dependencies
        with:
          qt-version: 6.10.3
          vcpkg-triplet: x64-windows-release

      - name: Get version
        uses: ./.github/actions/get-version

      - name: Configure
        run: ${{ env.CMAKE_CONFIGURE }} -G Ninja ${{ steps.get-deps.outputs.vcpkg-cmake-config }} -DPACKAGE_VERSION_LABEL="${{ env.DESKFLOW_PACKAGE_VERSION }}"

      - name: Build package
        run: cmake --build build --config Release -j8 --target package

      - name: Run tests
        uses: ./.github/actions/run-tests
        timeout-minutes: 5
        with:
          job: windows-2022-x64
